//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackathonBot.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить команду.
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, спишь? А работать когда? 😠.
        /// </summary>
        internal static string AdminHello {
            get {
                return ResourceManager.GetString("AdminHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string AdminModuleText {
            get {
                return ResourceManager.GetString("AdminModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ввод. Пожалуйста, попробуйте ещё раз.
        /// </summary>
        internal static string BaseModuleInvalidInput {
            get {
                return ResourceManager.GetString("BaseModuleInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейс успешно сменён.
        /// </summary>
        internal static string CaseChanged {
            get {
                return ResourceManager.GetString("CaseChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завод ЛД.
        /// </summary>
        internal static string CaseLD {
            get {
                return ResourceManager.GetString("CaseLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейсы.
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейс успешно выбран! Удачи на хакатоне!.
        /// </summary>
        internal static string CaseSelectedSuccessfully {
            get {
                return ResourceManager.GetString("CaseSelectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увы, но вы не можете выбрать кейс — произошло невероятное, и оба кейса были переполнены. Можете написать организатору по этому поводу: @kkkira_kh.
        /// </summary>
        internal static string CaseSelectionUnavailable {
            get {
                return ResourceManager.GetString("CaseSelectionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т-Банк.
        /// </summary>
        internal static string CaseTBank {
            get {
                return ResourceManager.GetString("CaseTBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить команду участника.
        /// </summary>
        internal static string ChangeParticipantTeam {
            get {
                return ResourceManager.GetString("ChangeParticipantTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить кейс команды.
        /// </summary>
        internal static string ChangeTeamCase {
            get {
                return ResourceManager.GetString("ChangeTeamCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ниже будет представлен список участников, сгруппированный по командам. Проверьте правильность введённых данных.
        /// </summary>
        internal static string CheckTeamUploadFileContents {
            get {
                return ResourceManager.GetString("CheckTeamUploadFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отправить сообщение?.
        /// </summary>
        internal static string ConfirmMailing {
            get {
                return ResourceManager.GetString("ConfirmMailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить команду?.
        /// </summary>
        internal static string ConfirmTeamDeletion {
            get {
                return ResourceManager.GetString("ConfirmTeamDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить сохранение?.
        /// </summary>
        internal static string ConfirmUpload {
            get {
                return ResourceManager.GetString("ConfirmUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить участника?.
        /// </summary>
        internal static string ConfirmUserDeletion {
            get {
                return ResourceManager.GetString("ConfirmUserDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить организатора.
        /// </summary>
        internal static string DeleteAdmin {
            get {
                return ResourceManager.GetString("DeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить участника.
        /// </summary>
        internal static string DeleteParticipant {
            get {
                return ResourceManager.GetString("DeleteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить команду.
        /// </summary>
        internal static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить решение команды.
        /// </summary>
        internal static string GetTeamSubmission {
            get {
                return ResourceManager.GetString("GetTeamSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хакатон.
        /// </summary>
        internal static string HackathonModuleText {
            get {
                return ResourceManager.GetString("HackathonModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ФИО участника.
        /// </summary>
        internal static string InputUserFullName {
            get {
                return ResourceManager.GetString("InputUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите никнейм пользователя.
        /// </summary>
        internal static string InputUserName {
            get {
                return ResourceManager.GetString("InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название команды:.
        /// </summary>
        internal static string InputUserTeam {
            get {
                return ResourceManager.GetString("InputUserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛД.
        /// </summary>
        internal static string LD {
            get {
                return ResourceManager.GetString("LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💫 Кейс от ЛД — разработка и внедрение системы машинного зрения для автоматического выявления брака при штамповке деталей.
        /// </summary>
        internal static string LDCaseInfo {
            get {
                return ResourceManager.GetString("LDCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка успешно выполнена. Отправлено {0} из {1}.
        /// </summary>
        internal static string MailingCompleted {
            get {
                return ResourceManager.GetString("MailingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали рассылки:
        ///
        ///От: {0}
        ///Показывать автора: {1}
        ///Кому: {2}
        ///
        ///Сообщение: {3}
        ///Цели рассылки: {4} пользователя(-ей), зарегистрировано и доступно {5}.
        /// </summary>
        internal static string MailingDetails {
            get {
                return ResourceManager.GetString("MailingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка отменена.
        /// </summary>
        internal static string MailingRejected {
            get {
                return ResourceManager.GetString("MailingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять организаторами.
        /// </summary>
        internal static string ManageOrganizers {
            get {
                return ResourceManager.GetString("ManageOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять командами.
        /// </summary>
        internal static string ManageTeams {
            get {
                return ResourceManager.GetString("ManageTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение для рассылки.
        /// </summary>
        internal static string MessageRequestPrompt {
            get {
                return ResourceManager.GetString("MessageRequestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string ModuleSelectRootMenu {
            get {
                return ResourceManager.GetString("ModuleSelectRootMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моё решение.
        /// </summary>
        internal static string MySubmission {
            get {
                return ResourceManager.GetString("MySubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя команда.
        /// </summary>
        internal static string MyTeam {
            get {
                return ResourceManager.GetString("MyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ещё не загрузили презентацию. Пожалуйста, прикрепите её до стоп-кода.
        /// </summary>
        internal static string NoPresentationYet {
            get {
                return ResourceManager.GetString("NoPresentationYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ещё не загрузили ссылку на репозиторий. Не забудьте прикрепить её до стоп-кода.
        /// </summary>
        internal static string NoRepoYet {
            get {
                return ResourceManager.GetString("NoRepoYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, что у вас нет команды. Пожалуйста, свяжитесь с организатором, чтобы вам помогли найти команду: @kkkira_kh.
        /// </summary>
        internal static string NoTeamWarning {
            get {
                return ResourceManager.GetString("NoTeamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылки.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организатор.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но вы не можете выполнить это действие. Попробуйте ещё раз или напишите разработчику: @IOException.
        /// </summary>
        internal static string OrganizerAccessDenied {
            get {
                return ResourceManager.GetString("OrganizerAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в бота &quot;ФакториХак&quot;! С его помощью вы можете осуществлять рассылки участникам и регистрировать результаты КММ. Выберите раздел меню для продолжения.
        /// </summary>
        internal static string OrganizerHello {
            get {
                return ResourceManager.GetString("OrganizerHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список организаторов:.
        /// </summary>
        internal static string OrganizersList {
            get {
                return ResourceManager.GetString("OrganizersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        internal static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но вы не можете выполнить это действие. Попробуйте ещё раз, или напишите организаторам хакатона: @kkkira_kh.
        /// </summary>
        internal static string ParticipantAccessDenied {
            get {
                return ResourceManager.GetString("ParticipantAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник: {0}
        ///Никнейм: {1}
        ///Регистрация в боте: {2}
        ///Команда: {3}.
        /// </summary>
        internal static string ParticipantDetails {
            get {
                return ResourceManager.GetString("ParticipantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Я – бот поддержки хакатона &quot;ФакториХак&quot;. С моей помощью ты сможешь участвовать в разных мероприятиях, а также выбирать кейсы и отправлять решения на них. Выбери раздел меню с помощью кнопок ниже :).
        /// </summary>
        internal static string ParticipantHello {
            get {
                return ResourceManager.GetString("ParticipantHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список участников:.
        /// </summary>
        internal static string ParticipantsList {
            get {
                return ResourceManager.GetString("ParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда участника изменена.
        /// </summary>
        internal static string ParticipantTeamChanged {
            get {
                return ResourceManager.GetString("ParticipantTeamChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с презентацией команды {0}.
        /// </summary>
        internal static string PresentationFileInfo {
            get {
                return ResourceManager.GetString("PresentationFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на презентацию команды {0}: {1}.
        /// </summary>
        internal static string PresentationLinkInfo {
            get {
                return ResourceManager.GetString("PresentationLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презентация успешно загружена!.
        /// </summary>
        internal static string PresentationUploaded {
            get {
                return ResourceManager.GetString("PresentationUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать организатора.
        /// </summary>
        internal static string RegisterAdmin {
            get {
                return ResourceManager.GetString("RegisterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать участника.
        /// </summary>
        internal static string RegisterParticipant {
            get {
                return ResourceManager.GetString("RegisterParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовать команду.
        /// </summary>
        internal static string RenameTeam {
            get {
                return ResourceManager.GetString("RenameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на репозиторий команды {0}: {1}.
        /// </summary>
        internal static string RepoLinkInfo {
            get {
                return ResourceManager.GetString("RepoLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на репозиторий успешно загружена!.
        /// </summary>
        internal static string RepoUploaded {
            get {
                return ResourceManager.GetString("RepoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой кейс вы выбираете?.
        /// </summary>
        internal static string RequestCasePrompt {
            get {
                return ResourceManager.GetString("RequestCasePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать кейс.
        /// </summary>
        internal static string SelectCase {
            get {
                return ResourceManager.GetString("SelectCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите цель рассылки.
        /// </summary>
        internal static string SelectMailingTarget {
            get {
                return ResourceManager.GetString("SelectMailingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите роль.
        /// </summary>
        internal static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие для команды.
        /// </summary>
        internal static string SelectTeamAction {
            get {
                return ResourceManager.GetString("SelectTeamAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие для пользователя.
        /// </summary>
        internal static string SelectUserAction {
            get {
                return ResourceManager.GetString("SelectUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить лично.
        /// </summary>
        internal static string SendPersonal {
            get {
                return ResourceManager.GetString("SendPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка всем участникам.
        /// </summary>
        internal static string SendToAllParticipants {
            get {
                return ResourceManager.GetString("SendToAllParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка всем.
        /// </summary>
        internal static string SendToEveryone {
            get {
                return ResourceManager.GetString("SendToEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка организаторам.
        /// </summary>
        internal static string SendToOrganizers {
            get {
                return ResourceManager.GetString("SendToOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение отдельной команде.
        /// </summary>
        internal static string SendToTeam {
            get {
                return ResourceManager.GetString("SendToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте CSV файл со списком участников для регистрации.
        /// </summary>
        internal static string SendUsersFile {
            get {
                return ResourceManager.GetString("SendUsersFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отобразить список участников.
        /// </summary>
        internal static string ShowParticipantsList {
            get {
                return ResourceManager.GetString("ShowParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите ли вы указать вас как автора рассылки?
        ///Если вы выберете &quot;Нет&quot;, то рассылка будет анонимной, если &quot;Да&quot; — то бот добавит подпись с вашим никнеймом в Telegram.
        /// </summary>
        internal static string ShowSenderNameRequest {
            get {
                return ResourceManager.GetString("ShowSenderNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т-Банк.
        /// </summary>
        internal static string TBank {
            get {
                return ResourceManager.GetString("TBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏰 Кейс от Т-банк — создание системы управления электронной очередью к интерактивным стендам компании.
        /// </summary>
        internal static string TBankCaseInfo {
            get {
                return ResourceManager.GetString("TBankCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда успешно удалена.
        /// </summary>
        internal static string TeamDeleted {
            get {
                return ResourceManager.GetString("TeamDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда {0}
        ///Участники:
        ///{1}
        ///
        ///Выбранный кейс: {2}
        ///Статус отправки решения:
        ///Презентация: {3}
        ///Репозиторий: {4}.
        /// </summary>
        internal static string TeamDetails {
            get {
                return ResourceManager.GetString("TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, {0}!
        ///
        ///Твоя команда: {1}
        ///Вы выбрали кейс: {2}.
        /// </summary>
        internal static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не найдена.
        /// </summary>
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда успешно переименована.
        /// </summary>
        internal static string TeamRenamed {
            get {
                return ResourceManager.GetString("TeamRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список команд:.
        /// </summary>
        internal static string TeamsList {
            get {
                return ResourceManager.GetString("TeamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка. Пожалуйста, сообщите разработчику @ioexception, приложив историю переписки..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, вы не были зарегистрированы на хакатон, поэтому это действие вам недоступно. Если вы считаете, что произошла ошибка, то напишите организаторам: @kkkira_kh.
        /// </summary>
        internal static string UnknownRoleAccessDenied {
            get {
                return ResourceManager.GetString("UnknownRoleAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но похоже вы не зарегистрированы! Пожалуйста, свяжитесь с организаторами хакатона: @kkkira_kh.
        /// </summary>
        internal static string UnknownRoleHello {
            get {
                return ResourceManager.GetString("UnknownRoleHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка успешно выполнена.
        /// </summary>
        internal static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите CSV файл со списком участников и их команд.
        /// </summary>
        internal static string UploadFilePrompt {
            get {
                return ResourceManager.GetString("UploadFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить список участников.
        /// </summary>
        internal static string UploadParticipantsList {
            get {
                return ResourceManager.GetString("UploadParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить презентацию.
        /// </summary>
        internal static string UploadPresentation {
            get {
                return ResourceManager.GetString("UploadPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите файл презентации или ссылку на него. Учтите, что бот не проверяет корректность ссылки, поэтому убедитесь, что она открывается..
        /// </summary>
        internal static string UploadPresentationPrompt {
            get {
                return ResourceManager.GetString("UploadPresentationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить ссылку на репозиторий.
        /// </summary>
        internal static string UploadRepo {
            get {
                return ResourceManager.GetString("UploadRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте ссылку на репозиторий с решением. Убедитесь, что репозиторий открыт для чтения.
        /// </summary>
        internal static string UploadRepoPrompt {
            get {
                return ResourceManager.GetString("UploadRepoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить решение.
        /// </summary>
        internal static string UploadSolution {
            get {
                return ResourceManager.GetString("UploadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, {0}!
        ///
        ///Твоя команда — {1}. На данный момент у вас следующий статус отправки решения:
        ///🌄 Презентация: {2}
        ///🖥️ Ссылка на репозиторий: {3}
        ///Последнее изменение {4}
        ///
        ///Выбери один из вариантов ниже, чтобы загрузить элементы решения.
        ///До стоп-кода осталось {5} ⏱️.
        /// </summary>
        internal static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно создан!.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким ником уже существует..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно удалён!.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль пользователя:.
        /// </summary>
        internal static string UserRoleInfo {
            get {
                return ResourceManager.GetString("UserRoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы хотите сделать?.
        /// </summary>
        internal static string WhatsYourChoice {
            get {
                return ResourceManager.GetString("WhatsYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
