//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackathonBot.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способности.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы больше не можете использовать эту способность..
        /// </summary>
        internal static string AbilityUsageLimitReached {
            get {
                return ResourceManager.GetString("AbilityUsageLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способность успешно применена.
        /// </summary>
        internal static string AbilityUsed {
            get {
                return ResourceManager.GetString("AbilityUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об игре.
        /// </summary>
        internal static string AboutKmm {
            get {
                return ResourceManager.GetString("AboutKmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша компания оказалась под угрозой: группа инсайдеров под прикрытием конкурента пытается захватить контроль над главным проектом — &quot;Сейфом с инновациями&quot;. За 3 дня команды получают роли (мирные или мафия) и соревнуются — мирные стремятся собрать 100 кредитов в общий сейф, мафия саботирует события, крадёт кредиты и пытается устранить ключевых защитников.
        ///
        ///Каждый день команды участвуют в мероприятиях и зарабатывают кредиты; ночью мафия тайно выбирает цель, а все мирные голосуют за подозреваемого. У каждой  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutKmmMessage {
            get {
                return ResourceManager.GetString("AboutKmmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить команду.
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, спишь? А работать когда? 😠.
        /// </summary>
        internal static string AdminHello {
            get {
                return ResourceManager.GetString("AdminHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string AdminModuleText {
            get {
                return ResourceManager.GetString("AdminModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание завершения голосования. Не покидайте это меню, не завершив голосование!.
        /// </summary>
        internal static string AwaitVoteEnd {
            get {
                return ResourceManager.GetString("AwaitVoteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В общем банке недостаточно денег для применения вашей способности.
        /// </summary>
        internal static string BankIsEmpty {
            get {
                return ResourceManager.GetString("BankIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ввод. Пожалуйста, попробуйте ещё раз.
        /// </summary>
        internal static string BaseModuleInvalidInput {
            get {
                return ResourceManager.GetString("BaseModuleInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейс успешно сменён.
        /// </summary>
        internal static string CaseChanged {
            get {
                return ResourceManager.GetString("CaseChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завод ЛД.
        /// </summary>
        internal static string CaseLD {
            get {
                return ResourceManager.GetString("CaseLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейсы.
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейс успешно выбран! Удачи на хакатоне!.
        /// </summary>
        internal static string CaseSelectedSuccessfully {
            get {
                return ResourceManager.GetString("CaseSelectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увы, но вы не можете выбрать кейс — произошло невероятное, и оба кейса были переполнены. Можете написать организатору по этому поводу: @kkkira_kh.
        /// </summary>
        internal static string CaseSelectionUnavailable {
            get {
                return ResourceManager.GetString("CaseSelectionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т-Банк.
        /// </summary>
        internal static string CaseTBank {
            get {
                return ResourceManager.GetString("CaseTBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить команду участника.
        /// </summary>
        internal static string ChangeParticipantTeam {
            get {
                return ResourceManager.GetString("ChangeParticipantTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить кейс команды.
        /// </summary>
        internal static string ChangeTeamCase {
            get {
                return ResourceManager.GetString("ChangeTeamCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту способность перед каждым голосованием, чтобы определить, какая команда является мафией. До конца общего голосования вы можете менять выбор, а после него вам придёт сообщение с информацией по выбранной вами команде. После голосования вы снова можете использовать эту способность, чтобы выбирать другие команды.
        /// </summary>
        internal static string CheckDescription {
            get {
                return ResourceManager.GetString("CheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ниже будет представлен список участников, сгруппированный по командам. Проверьте правильность введённых данных.
        /// </summary>
        internal static string CheckTeamUploadFileContents {
            get {
                return ResourceManager.GetString("CheckTeamUploadFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        internal static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить голосование.
        /// </summary>
        internal static string ConcludeVote {
            get {
                return ResourceManager.GetString("ConcludeVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите использовать способность?.
        /// </summary>
        internal static string ConfirmAbilityUsage {
            get {
                return ResourceManager.GetString("ConfirmAbilityUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить событие?.
        /// </summary>
        internal static string ConfirmEventDeletion {
            get {
                return ResourceManager.GetString("ConfirmEventDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите заново начать игру в мафию? Это удалит все текущие команды и весь прогресс.
        /// </summary>
        internal static string ConfirmInitializeKmm {
            get {
                return ResourceManager.GetString("ConfirmInitializeKmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отправить сообщение?.
        /// </summary>
        internal static string ConfirmMailing {
            get {
                return ResourceManager.GetString("ConfirmMailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить квест?.
        /// </summary>
        internal static string ConfirmQuestDeletion {
            get {
                return ResourceManager.GetString("ConfirmQuestDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить команду?.
        /// </summary>
        internal static string ConfirmTeamDeletion {
            get {
                return ResourceManager.GetString("ConfirmTeamDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить сохранение?.
        /// </summary>
        internal static string ConfirmUpload {
            get {
                return ResourceManager.GetString("ConfirmUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить участника?.
        /// </summary>
        internal static string ConfirmUserDeletion {
            get {
                return ResourceManager.GetString("ConfirmUserDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша команда: {0}
        ///Вы ещё не сделали голос.
        /// </summary>
        internal static string CurrentVoteDefailsNoVote {
            get {
                return ResourceManager.GetString("CurrentVoteDefailsNoVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша команда: {0}
        ///Вы выбрали команду {1}.
        /// </summary>
        internal static string CurrentVoteDetails {
            get {
                return ResourceManager.GetString("CurrentVoteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утечка данных.
        /// </summary>
        internal static string DataLeak {
            get {
                return ResourceManager.GetString("DataLeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта способность позволяет уменьшить общий счёт мирных жителей на 10 единиц. Стоимость использования: 10 личных монет..
        /// </summary>
        internal static string DataLeakDescription {
            get {
                return ResourceManager.GetString("DataLeakDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защита.
        /// </summary>
        internal static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту способность перед каждым голосованием, чтобы защитить одну команду (в том числе и себя) от нападения мафии. Учтите, что эта способность не подействует, если вас выгонят на голосовании. Вы можете менять свой выбор сколько угодно раз до конца голосования. После голосования не будет раскрыто, за кого вы голосовали, но ваш последний голос учтётся при проверке жертвы мафии.
        /// </summary>
        internal static string DefenseDescription {
            get {
                return ResourceManager.GetString("DefenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить организатора.
        /// </summary>
        internal static string DeleteAdmin {
            get {
                return ResourceManager.GetString("DeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить событие.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить участника.
        /// </summary>
        internal static string DeleteParticipant {
            get {
                return ResourceManager.GetString("DeleteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить квест.
        /// </summary>
        internal static string DeleteQuest {
            get {
                return ResourceManager.GetString("DeleteQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить команду.
        /// </summary>
        internal static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тимлид.
        /// </summary>
        internal static string Detective {
            get {
                return ResourceManager.GetString("Detective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детектив столкнулся с помехами и не смог никого вычислить.
        /// </summary>
        internal static string DetectiveCheckBlocked {
            get {
                return ResourceManager.GetString("DetectiveCheckBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат проверки команды &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string DetectiveCheckResult {
            get {
                return ResourceManager.GetString("DetectiveCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детектив вычислил мирного жителя.
        /// </summary>
        internal static string DetectiveFoundCitizen {
            get {
                return ResourceManager.GetString("DetectiveFoundCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детектив вычислил мафию.
        /// </summary>
        internal static string DetectiveFoundMafia {
            get {
                return ResourceManager.GetString("DetectiveFoundMafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специалист по информационной безопасности.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить описание квеста.
        /// </summary>
        internal static string EditQuestDescription {
            get {
                return ResourceManager.GetString("EditQuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить имя квеста.
        /// </summary>
        internal static string EditQuestName {
            get {
                return ResourceManager.GetString("EditQuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить событие.
        /// </summary>
        internal static string EndEvent {
            get {
                return ResourceManager.GetString("EndEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие уже существует.
        /// </summary>
        internal static string EventAlreadyExists {
            get {
                return ResourceManager.GetString("EventAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для события &apos;{0}&apos; команде &apos;{1}&apos; назначен индивидуальный квест!
        ///
        ///{2}
        ///{3}
        ///
        ///Выполнение этого квеста командой даст бонус к очкам мирным жителям или позволит мафии украсть часть очков. Организатор КММ сам проследит за выполнением этого квеста..
        /// </summary>
        internal static string EventAssignedQuest {
            get {
                return ResourceManager.GetString("EventAssignedQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие успешно создано.
        /// </summary>
        internal static string EventCreated {
            get {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие успешно удалено.
        /// </summary>
        internal static string EventDeleted {
            get {
                return ResourceManager.GetString("EventDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие успешно завершено.
        /// </summary>
        internal static string EventEndedSuccessfully {
            get {
                return ResourceManager.GetString("EventEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты мероприятия &apos;{0}&apos; для команды &apos;{1}&apos;.
        ///Место: {2}
        ///Выполнение квеста: {3}
        ///Итоговый счёт команды: {4}.
        /// </summary>
        internal static string EventFinalResultForTeam {
            get {
                return ResourceManager.GetString("EventFinalResultForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У события нет квестов.
        /// </summary>
        internal static string EventHasNoQuests {
            get {
                return ResourceManager.GetString("EventHasNoQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список событий:.
        /// </summary>
        internal static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие успешно запущено.
        /// </summary>
        internal static string EventStartedSuccessfully {
            get {
                return ResourceManager.GetString("EventStartedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брандмауер.
        /// </summary>
        internal static string Firewall {
            get {
                return ResourceManager.GetString("Firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта способность позволяет заблокировать использование способностей мафии при следующем срабатывании. Её можно использовать только один раз за игру. .
        /// </summary>
        internal static string FirewallDescription {
            get {
                return ResourceManager.GetString("FirewallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить решение команды.
        /// </summary>
        internal static string GetTeamSubmission {
            get {
                return ResourceManager.GetString("GetTeamSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания-конкурент.
        /// </summary>
        internal static string Godfather {
            get {
                return ResourceManager.GetString("Godfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хакатон уже завершился!.
        /// </summary>
        internal static string HackathonEndedWarning {
            get {
                return ResourceManager.GetString("HackathonEndedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хакатон.
        /// </summary>
        internal static string HackathonModuleText {
            get {
                return ResourceManager.GetString("HackathonModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хакерская атака.
        /// </summary>
        internal static string HackerAttack {
            get {
                return ResourceManager.GetString("HackerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта способность позволяет заблокировать способности &quot;Защита&quot; и &quot;Проверка&quot; на один круг голосования. Стоимость: 10 личных монет.
        /// </summary>
        internal static string HackerAttackDescription {
            get {
                return ResourceManager.GetString("HackerAttackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздать роли командам.
        /// </summary>
        internal static string InitializeKmm {
            get {
                return ResourceManager.GetString("InitializeKmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название события.
        /// </summary>
        internal static string InputEventName {
            get {
                return ResourceManager.GetString("InputEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите награду за первое место.
        /// </summary>
        internal static string InputFirstPlaceReward {
            get {
                return ResourceManager.GetString("InputFirstPlaceReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое описание квеста.
        /// </summary>
        internal static string InputNewQuestDescription {
            get {
                return ResourceManager.GetString("InputNewQuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое имя квеста.
        /// </summary>
        internal static string InputNewQuestName {
            get {
                return ResourceManager.GetString("InputNewQuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание квеста.
        /// </summary>
        internal static string InputQuestDescription {
            get {
                return ResourceManager.GetString("InputQuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя квеста.
        /// </summary>
        internal static string InputQuestName {
            get {
                return ResourceManager.GetString("InputQuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите награду за второе место.
        /// </summary>
        internal static string InputSecondPlaceReward {
            get {
                return ResourceManager.GetString("InputSecondPlaceReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите награду за третье место.
        /// </summary>
        internal static string InputThirdPlaceReward {
            get {
                return ResourceManager.GetString("InputThirdPlaceReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ФИО участника.
        /// </summary>
        internal static string InputUserFullName {
            get {
                return ResourceManager.GetString("InputUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите никнейм пользователя.
        /// </summary>
        internal static string InputUserName {
            get {
                return ResourceManager.GetString("InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название команды:.
        /// </summary>
        internal static string InputUserTeam {
            get {
                return ResourceManager.GetString("InputUserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный выбор команды.
        /// </summary>
        internal static string InvalidTeamSelection {
            get {
                return ResourceManager.GetString("InvalidTeamSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КММ.
        /// </summary>
        internal static string Kmm {
            get {
                return ResourceManager.GetString("Kmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог способностей.
        /// </summary>
        internal static string KmmAuditAbilities {
            get {
                return ResourceManager.GetString("KmmAuditAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать событие.
        /// </summary>
        internal static string KmmCreateEvent {
            get {
                return ResourceManager.GetString("KmmCreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать квест/саботаж.
        /// </summary>
        internal static string KmmCreateQuest {
            get {
                return ResourceManager.GetString("KmmCreateQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра для КММ успешно инициализирована.
        /// </summary>
        internal static string KmmInitializedSuccessfully {
            get {
                return ResourceManager.GetString("KmmInitializedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять событиями.
        /// </summary>
        internal static string KmmManageEvents {
            get {
                return ResourceManager.GetString("KmmManageEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление КММ.
        /// </summary>
        internal static string KmmManagement {
            get {
                return ResourceManager.GetString("KmmManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять квестами.
        /// </summary>
        internal static string KmmManageQuests {
            get {
                return ResourceManager.GetString("KmmManageQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление действующим событием. Внимание, не покидайте это меню без завершения события!.
        /// </summary>
        internal static string KmmManageRunningEvent {
            get {
                return ResourceManager.GetString("KmmManageRunningEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КММ не инициализировано. Распределите команды по ролям, чтобы использовать остальные функции..
        /// </summary>
        internal static string KmmNotInitialized {
            get {
                return ResourceManager.GetString("KmmNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но мероприятия ещё не начались, либо вы на них не зарегистрированы. Подождите ещё немного, скоро организаторы зарегистрируют всех желающих. Если вы считаете, что произошла какая-то ошибка, то напишите организаторам: @kkkira_kh.
        /// </summary>
        internal static string KmmNotStarted {
            get {
                return ResourceManager.GetString("KmmNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать голосование.
        /// </summary>
        internal static string KmmStartVote {
            get {
                return ResourceManager.GetString("KmmStartVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда {0}:
        ///Роль: {1}
        ///Команда жива? {2}
        ///Счёт: {3}.
        /// </summary>
        internal static string KmmTeamDetails {
            get {
                return ResourceManager.GetString("KmmTeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша команда по КММ: {0}
        ///Роль команды: {1}
        ///Заработанные очки: {2}
        ///{3}
        ///
        ///Общий банк мирных жителей: {4}/{5}.
        /// </summary>
        internal static string KmmTeamInfo {
            get {
                return ResourceManager.GetString("KmmTeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статусы команд.
        /// </summary>
        internal static string KmmTeamsStatus {
            get {
                return ResourceManager.GetString("KmmTeamsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛД.
        /// </summary>
        internal static string LD {
            get {
                return ResourceManager.GetString("LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💫 Кейс от ЛД — разработка и внедрение системы машинного зрения для автоматического выявления брака при штамповке деталей.
        /// </summary>
        internal static string LDCaseInfo {
            get {
                return ResourceManager.GetString("LDCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить список квестов по командам.
        /// </summary>
        internal static string ListTeamQuests {
            get {
                return ResourceManager.GetString("ListTeamQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список команд, оставшихся в живых.
        /// </summary>
        internal static string LiveTeams {
            get {
                return ResourceManager.GetString("LiveTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жители изгнали команду &apos;{0}&apos;..
        /// </summary>
        internal static string LynchedResult {
            get {
                return ResourceManager.GetString("LynchedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жители никого не изгнали.
        /// </summary>
        internal static string LynchedResultNone {
            get {
                return ResourceManager.GetString("LynchedResultNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инсайдер.
        /// </summary>
        internal static string Mafia {
            get {
                return ResourceManager.GetString("Mafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мафия изгнала команду &apos;{0}&apos;..
        /// </summary>
        internal static string MafiaKillResult {
            get {
                return ResourceManager.GetString("MafiaKillResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мафия никого не убила.
        /// </summary>
        internal static string MafiaKillResultNone {
            get {
                return ResourceManager.GetString("MafiaKillResultNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный счёт мафии: {0}.
        /// </summary>
        internal static string MafiaPersonalBankInfo {
            get {
                return ResourceManager.GetString("MafiaPersonalBankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка успешно выполнена. Отправлено {0} из {1}.
        /// </summary>
        internal static string MailingCompleted {
            get {
                return ResourceManager.GetString("MailingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали рассылки:
        ///
        ///От: {0}
        ///Показывать автора: {1}
        ///Кому: {2}
        ///
        ///Сообщение: {3}
        ///Цели рассылки: {4} пользователя(-ей), зарегистрировано и доступно {5}.
        /// </summary>
        internal static string MailingDetails {
            get {
                return ResourceManager.GetString("MailingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка отменена.
        /// </summary>
        internal static string MailingRejected {
            get {
                return ResourceManager.GetString("MailingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять организаторами.
        /// </summary>
        internal static string ManageOrganizers {
            get {
                return ResourceManager.GetString("ManageOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управлять командами.
        /// </summary>
        internal static string ManageTeams {
            get {
                return ResourceManager.GetString("ManageTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение для рассылки.
        /// </summary>
        internal static string MessageRequestPrompt {
            get {
                return ResourceManager.GetString("MessageRequestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string ModuleSelectRootMenu {
            get {
                return ResourceManager.GetString("ModuleSelectRootMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моё решение.
        /// </summary>
        internal static string MySubmission {
            get {
                return ResourceManager.GetString("MySubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя команда.
        /// </summary>
        internal static string MyTeam {
            get {
                return ResourceManager.GetString("MyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя уже занято.
        /// </summary>
        internal static string NameTaken {
            get {
                return ResourceManager.GetString("NameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ещё не загрузили презентацию. Пожалуйста, прикрепите её до стоп-кода.
        /// </summary>
        internal static string NoPresentationYet {
            get {
                return ResourceManager.GetString("NoPresentationYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет квестов.
        /// </summary>
        internal static string NoQuests {
            get {
                return ResourceManager.GetString("NoQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ещё не загрузили ссылку на репозиторий. Не забудьте прикрепить её до стоп-кода.
        /// </summary>
        internal static string NoRepoYet {
            get {
                return ResourceManager.GetString("NoRepoYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список квестов.
        /// </summary>
        internal static string NormalQuestsList {
            get {
                return ResourceManager.GetString("NormalQuestsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет команд для запуска события.
        /// </summary>
        internal static string NoTeamsForEvent {
            get {
                return ResourceManager.GetString("NoTeamsForEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, что у вас нет команды. Пожалуйста, свяжитесь с организатором, чтобы вам помогли найти команду: @kkkira_kh.
        /// </summary>
        internal static string NoTeamWarning {
            get {
                return ResourceManager.GetString("NoTeamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно денег для использования этой способности.
        /// </summary>
        internal static string NotEnoughCoins {
            get {
                return ResourceManager.GetString("NotEnoughCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылки.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не реализовано.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организатор.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но вы не можете выполнить это действие. Попробуйте ещё раз или напишите разработчику: @IOExcept10n.
        /// </summary>
        internal static string OrganizerAccessDenied {
            get {
                return ResourceManager.GetString("OrganizerAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в бота &quot;ФакториХак&quot;! С его помощью вы можете осуществлять рассылки участникам и регистрировать результаты КММ. Выберите раздел меню для продолжения.
        /// </summary>
        internal static string OrganizerHello {
            get {
                return ResourceManager.GetString("OrganizerHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список организаторов:.
        /// </summary>
        internal static string OrganizersList {
            get {
                return ResourceManager.GetString("OrganizersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        internal static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но вы не можете выполнить это действие. Попробуйте ещё раз, или напишите организаторам хакатона: @kkkira_kh.
        /// </summary>
        internal static string ParticipantAccessDenied {
            get {
                return ResourceManager.GetString("ParticipantAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник: {0}
        ///Никнейм: {1}
        ///Регистрация в боте: {2}
        ///Команда: {3}.
        /// </summary>
        internal static string ParticipantDetails {
            get {
                return ResourceManager.GetString("ParticipantDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Я – бот поддержки хакатона &quot;ФакториХак&quot;. С моей помощью ты сможешь участвовать в разных мероприятиях, а также выбирать кейсы и отправлять решения на них. Выбери раздел меню с помощью кнопок ниже :).
        /// </summary>
        internal static string ParticipantHello {
            get {
                return ResourceManager.GetString("ParticipantHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список участников:.
        /// </summary>
        internal static string ParticipantsList {
            get {
                return ResourceManager.GetString("ParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда участника изменена.
        /// </summary>
        internal static string ParticipantTeamChanged {
            get {
                return ResourceManager.GetString("ParticipantTeamChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите команду, занявшую {0} место:.
        /// </summary>
        internal static string PickNextPlace {
            get {
                return ResourceManager.GetString("PickNextPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите команду для регистрации результата.
        /// </summary>
        internal static string PickTeamToProcess {
            get {
                return ResourceManager.GetString("PickTeamToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с презентацией команды {0}.
        /// </summary>
        internal static string PresentationFileInfo {
            get {
                return ResourceManager.GetString("PresentationFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на презентацию команды {0}: {1}.
        /// </summary>
        internal static string PresentationLinkInfo {
            get {
                return ResourceManager.GetString("PresentationLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презентация успешно загружена!.
        /// </summary>
        internal static string PresentationUploaded {
            get {
                return ResourceManager.GetString("PresentationUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите место, занятое командой.
        /// </summary>
        internal static string PromptPlace {
            get {
                return ResourceManager.GetString("PromptPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда выполнила квест?.
        /// </summary>
        internal static string PromptQuestCompleted {
            get {
                return ResourceManager.GetString("PromptQuestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест успешно создан.
        /// </summary>
        internal static string QuestCreatedSuccessfully {
            get {
                return ResourceManager.GetString("QuestCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест успешно удалён.
        /// </summary>
        internal static string QuestDeleted {
            get {
                return ResourceManager.GetString("QuestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест успешно обновлён.
        /// </summary>
        internal static string QuestUpdated {
            get {
                return ResourceManager.GetString("QuestUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать организатора.
        /// </summary>
        internal static string RegisterAdmin {
            get {
                return ResourceManager.GetString("RegisterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать участника.
        /// </summary>
        internal static string RegisterParticipant {
            get {
                return ResourceManager.GetString("RegisterParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовать команду.
        /// </summary>
        internal static string RenameTeam {
            get {
                return ResourceManager.GetString("RenameTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на репозиторий команды {0}: {1}.
        /// </summary>
        internal static string RepoLinkInfo {
            get {
                return ResourceManager.GetString("RepoLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на репозиторий успешно загружена!.
        /// </summary>
        internal static string RepoUploaded {
            get {
                return ResourceManager.GetString("RepoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой кейс вы выбираете?.
        /// </summary>
        internal static string RequestCasePrompt {
            get {
                return ResourceManager.GetString("RequestCasePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список саботажей.
        /// </summary>
        internal static string SabotageQuestsList {
            get {
                return ResourceManager.GetString("SabotageQuestsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способность.
        /// </summary>
        internal static string SelectAbility {
            get {
                return ResourceManager.GetString("SelectAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать кейс.
        /// </summary>
        internal static string SelectCase {
            get {
                return ResourceManager.GetString("SelectCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите событие.
        /// </summary>
        internal static string SelectEvent {
            get {
                return ResourceManager.GetString("SelectEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите цель рассылки.
        /// </summary>
        internal static string SelectMailingTarget {
            get {
                return ResourceManager.GetString("SelectMailingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите квест.
        /// </summary>
        internal static string SelectQuest {
            get {
                return ResourceManager.GetString("SelectQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это квест для саботажа?.
        /// </summary>
        internal static string SelectQuestIsSabotage {
            get {
                return ResourceManager.GetString("SelectQuestIsSabotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите роль.
        /// </summary>
        internal static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите команду.
        /// </summary>
        internal static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие для команды.
        /// </summary>
        internal static string SelectTeamAction {
            get {
                return ResourceManager.GetString("SelectTeamAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие для пользователя.
        /// </summary>
        internal static string SelectUserAction {
            get {
                return ResourceManager.GetString("SelectUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите следующую команду для записи результатов.
        /// </summary>
        internal static string SelectWinners {
            get {
                return ResourceManager.GetString("SelectWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить лично.
        /// </summary>
        internal static string SendPersonal {
            get {
                return ResourceManager.GetString("SendPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка всем участникам.
        /// </summary>
        internal static string SendToAllParticipants {
            get {
                return ResourceManager.GetString("SendToAllParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка всем.
        /// </summary>
        internal static string SendToEveryone {
            get {
                return ResourceManager.GetString("SendToEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассылка организаторам.
        /// </summary>
        internal static string SendToOrganizers {
            get {
                return ResourceManager.GetString("SendToOrganizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение отдельной команде.
        /// </summary>
        internal static string SendToTeam {
            get {
                return ResourceManager.GetString("SendToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте CSV файл со списком участников для регистрации.
        /// </summary>
        internal static string SendUsersFile {
            get {
                return ResourceManager.GetString("SendUsersFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать кейс команды.
        /// </summary>
        internal static string SetTeamCase {
            get {
                return ResourceManager.GetString("SetTeamCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отобразить список участников.
        /// </summary>
        internal static string ShowParticipantsList {
            get {
                return ResourceManager.GetString("ShowParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотите ли вы указать вас как автора рассылки?
        ///Если вы выберете &quot;Нет&quot;, то рассылка будет анонимной, если &quot;Да&quot; — то бот добавит подпись с вашим никнеймом в Telegram.
        /// </summary>
        internal static string ShowSenderNameRequest {
            get {
                return ResourceManager.GetString("ShowSenderNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клевета.
        /// </summary>
        internal static string Slander {
            get {
                return ResourceManager.GetString("Slander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта способность лишает выбранную команду голоса на следующем голосовании. Стоимость использования: 5 личных монет. Каждое повторное использование способности в рамках одного голосования позволяет выбрать ещё одну команду в качестве цели.
        /// </summary>
        internal static string SlanderDescription {
            get {
                return ResourceManager.GetString("SlanderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить событие.
        /// </summary>
        internal static string StartEvent {
            get {
                return ResourceManager.GetString("StartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Т-Банк.
        /// </summary>
        internal static string TBank {
            get {
                return ResourceManager.GetString("TBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏰 Кейс от Т-банк — создание системы управления электронной очередью к интерактивным стендам компании.
        /// </summary>
        internal static string TBankCaseInfo {
            get {
                return ResourceManager.GetString("TBankCaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кейс команды выбран успешно.
        /// </summary>
        internal static string TeamCaseSet {
            get {
                return ResourceManager.GetString("TeamCaseSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда успешно удалена.
        /// </summary>
        internal static string TeamDeleted {
            get {
                return ResourceManager.GetString("TeamDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда {0}
        ///Участники:
        ///{1}
        ///
        ///Выбранный кейс: {2}
        ///Статус отправки решения:
        ///Презентация: {3}
        ///Репозиторий: {4}.
        /// </summary>
        internal static string TeamDetails {
            get {
                return ResourceManager.GetString("TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, {0}!
        ///
        ///Твоя команда: {1}
        ///Вы выбрали кейс: {2}.
        /// </summary>
        internal static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не найдена.
        /// </summary>
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда выбыла!.
        /// </summary>
        internal static string TeamOut {
            get {
                return ResourceManager.GetString("TeamOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не беспокойтесь, вы всё ещё можете копить очки в общий зачёт, но они не будут засчитываться в банке.
        /// </summary>
        internal static string TeamOutNote {
            get {
                return ResourceManager.GetString("TeamOutNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда успешно переименована.
        /// </summary>
        internal static string TeamRenamed {
            get {
                return ResourceManager.GetString("TeamRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список команд:.
        /// </summary>
        internal static string TeamsList {
            get {
                return ResourceManager.GetString("TeamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка. Пожалуйста, сообщите разработчику @ioexcept10n, приложив историю переписки..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, вы не были зарегистрированы на хакатон, поэтому это действие вам недоступно. Если вы считаете, что произошла ошибка, то напишите организаторам: @kkkira_kh.
        /// </summary>
        internal static string UnknownRoleAccessDenied {
            get {
                return ResourceManager.GetString("UnknownRoleAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но похоже вы не зарегистрированы! Пожалуйста, свяжитесь с организаторами хакатона: @kkkira_kh.
        /// </summary>
        internal static string UnknownRoleHello {
            get {
                return ResourceManager.GetString("UnknownRoleHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка успешно выполнена.
        /// </summary>
        internal static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите CSV файл со списком участников и их команд.
        /// </summary>
        internal static string UploadFilePrompt {
            get {
                return ResourceManager.GetString("UploadFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить список участников.
        /// </summary>
        internal static string UploadParticipantsList {
            get {
                return ResourceManager.GetString("UploadParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить презентацию.
        /// </summary>
        internal static string UploadPresentation {
            get {
                return ResourceManager.GetString("UploadPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите файл презентации или ссылку на него. Учтите, что бот не проверяет корректность ссылки, поэтому убедитесь, что она открывается..
        /// </summary>
        internal static string UploadPresentationPrompt {
            get {
                return ResourceManager.GetString("UploadPresentationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить ссылку на репозиторий.
        /// </summary>
        internal static string UploadRepo {
            get {
                return ResourceManager.GetString("UploadRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте ссылку на репозиторий с решением. Убедитесь, что репозиторий открыт для чтения.
        /// </summary>
        internal static string UploadRepoPrompt {
            get {
                return ResourceManager.GetString("UploadRepoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить решение.
        /// </summary>
        internal static string UploadSolution {
            get {
                return ResourceManager.GetString("UploadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, {0}!
        ///
        ///Твоя команда — {1}. На данный момент у вас следующий статус отправки решения:
        ///🌄 Презентация: {2}
        ///🖥️ Ссылка на репозиторий: {3}
        ///Последнее изменение {4}
        ///
        ///Выбери один из вариантов ниже, чтобы загрузить элементы решения.
        ///До стоп-кода осталось {5} ⏱️.
        /// </summary>
        internal static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите CSV-файл со списком команд-участников и их цветов.
        /// </summary>
        internal static string UploadTeamsPrompt {
            get {
                return ResourceManager.GetString("UploadTeamsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно создан!.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким ником уже существует..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно удалён!.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль пользователя:.
        /// </summary>
        internal static string UserRoleInfo {
            get {
                return ResourceManager.GetString("UserRoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосование.
        /// </summary>
        internal static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш голос принят!.
        /// </summary>
        internal static string VoteAccepted {
            get {
                return ResourceManager.GetString("VoteAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосование на данный момент закрыто. Пожалуйста, попробуйте позже.
        /// </summary>
        internal static string VoteClosedWarning {
            get {
                return ResourceManager.GetString("VoteClosedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосование успешно завершено!.
        /// </summary>
        internal static string VoteEndedSuccessfully {
            get {
                return ResourceManager.GetString("VoteEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пришло время голосования! Заходи в раздел для КММ и отдай свой голос!.
        /// </summary>
        internal static string VoteStartedMessage {
            get {
                return ResourceManager.GetString("VoteStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите команду, за которую вы голосвуете.
        /// </summary>
        internal static string VoteTargetRequest {
            get {
                return ResourceManager.GetString("VoteTargetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы хотите сделать?.
        /// </summary>
        internal static string WhatsYourChoice {
            get {
                return ResourceManager.GetString("WhatsYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудовая этика.
        /// </summary>
        internal static string WorkEthic {
            get {
                return ResourceManager.GetString("WorkEthic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете использовать эту способность один раз за всю игру, чтобы увеличить число заработанных в следующем мероприятии личных очков в 2 раза.
        /// </summary>
        internal static string WorkEthicDescription {
            get {
                return ResourceManager.GetString("WorkEthicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы также можете загрузить CSV файл с результатами мероприятия.
        /// </summary>
        internal static string YouCanAlsoInputCSVWithResults {
            get {
                return ResourceManager.GetString("YouCanAlsoInputCSVWithResults", resourceCulture);
            }
        }
    }
}
